# Generated by Django 4.2.3 on 2023-07-12 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("locks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lockrequest",
            name="user1",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user1",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="lockrequest",
            name="user2",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user2",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
