# Generated by Django 4.2.3 on 2023-07-12 14:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locks", "0002_alter_lockrequest_user1_alter_lockrequest_user2"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LockPost",
        ),
    ]
