# Generated by Django 4.2.3 on 2023-07-12 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_customuser_lock_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_is_reciever",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_is_sender",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_locked_with",
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="lock_count",
            field=models.PositiveIntegerField(
                default=7,
                validators=[
                    django.core.validators.MaxValueValidator(7),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
    ]
