# Generated by Django 4.2.3 on 2023-07-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_customuser_user_is_reciever_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="lock_exist",
            field=models.BooleanField(default=False),
        ),
    ]
