# Generated by Django 4.2.3 on 2023-07-12 18:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_customuser_lock_exist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="lock_exist",
            new_name="padlock_exist",
        ),
    ]
