# Generated by Django 4.2.3 on 2023-07-12 19:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_rename_lock_exist_customuser_padlock_exist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="padlock_exist",
        ),
    ]
