# Generated by Django 4.2.3 on 2023-07-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_remove_customuser_padlock_exist"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="lock_exist",
            field=models.BooleanField(default=False),
        ),
    ]
