# Generated by Django 4.2.3 on 2023-07-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_customuser_lock_exist"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="lock_published",
            field=models.BooleanField(default=False),
        ),
    ]
