# Generated by Django 4.2.3 on 2023-07-21 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("padlocks", "0011_alter_padlock_story_field"),
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="padlocks.padlock",
            ),
        ),
    ]
