# Generated by Django 4.2.3 on 2023-07-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("padlocks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="padlock",
            name="lock_nature",
            field=models.TextField(
                choices=[("Story", "Story"), ("Motto", "Motto")],
                default="Story",
                max_length=5,
            ),
        ),
    ]
