# Generated by Django 4.2.3 on 2023-07-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("padlocks", "0006_alter_padlock_active_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="padlock",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
