# Generated by Django 4.2.3 on 2023-07-16 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("padlocks", "0008_alter_padlock_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="padlock",
            name="start_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
