# Generated by Django 4.2.3 on 2023-07-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("padlocks", "0011_alter_padlock_story_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="padlock",
            name="lock_nature",
            field=models.TextField(
                choices=[("Story", "Story"), ("Motto", "Motto")],
                default="Story",
                max_length=5,
                null=True,
            ),
        ),
    ]
